# Generated by Django 5.0.1 on 2024-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=6)),
                ('Area_detail', models.CharField(max_length=5)),
                ('address_code', models.CharField(max_length=10)),
                ('Weather_forecast_code', models.CharField(max_length=8)),
                ('Temperature_code', models.CharField(max_length=8)),
                ('X', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Y', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('ID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Date', models.CharField(max_length=8)),
                ('regId', models.CharField(max_length=8)),
                ('taMin3', models.SmallIntegerField()),
                ('taMax3', models.SmallIntegerField()),
                ('taMin4', models.SmallIntegerField()),
                ('taMax4', models.SmallIntegerField()),
                ('taMin5', models.SmallIntegerField()),
                ('taMax5', models.SmallIntegerField()),
                ('taMin6', models.SmallIntegerField()),
                ('taMax6', models.SmallIntegerField()),
                ('taMin7', models.SmallIntegerField()),
                ('taMax7', models.SmallIntegerField()),
                ('taMin8', models.SmallIntegerField()),
                ('taMax8', models.SmallIntegerField()),
                ('taMin9', models.SmallIntegerField()),
                ('taMax9', models.SmallIntegerField()),
                ('taMin10', models.SmallIntegerField()),
                ('taMax10', models.SmallIntegerField()),
            ],
        ),
    ]
