# Generated by Django 5.0.1 on 2024-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_area_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edate', models.DateField()),
                ('edesc', models.TextField()),
                ('ecolor', models.CharField(max_length=20)),
                ('eicon', models.CharField(max_length=20)),
            ],
        ),
    ]
