# Generated by Django 5.0.1 on 2024-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_eventmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='ecolor',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='eicon',
        ),
    ]
