# Generated by Django 5.0.2 on 2024-02-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cal", "0004_remove_eventmodel_ecolor_remove_eventmodel_eicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="edate",
            field=models.CharField(max_length=100),
        ),
    ]
